# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    tags: 'v*'

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Deploy to S3"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          
      - name: "Install and Build"
        run: |
          npm install -g yarn
          npm install --frozen-lockfile
          yarn install
          yarn run release
      
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
#       - name: "Sync with S3"
#         run: aws s3 sync ./docs/.vuepress/dist/ s3://help.photosynq.com/ --acl public-read --delete
